### ISSUE TITLE
Backend throws "No path provided error"

### ISSUE THREAD

**Issue by sveltarne** [Deftu/Deftbin#4]
You can find the full error thrown at https://deftb.in/fifylibuma.js.
Steps to reproduce: 
Clone the repository
Install the dependencies in both the backend and frontend directories using `npm install`.
Run the backend using `npm start` in the backend directory

**Comment by Deftu** [comment]
I forgot to specify that you need to define a `path` option inside of your config, however this has been replaced with using a collection inside of the MongoDB database in the dev version. For now, define a directory path in your config like so:
```json
{
    "store": {
        "options": {
            "path": "documents"
        }
    }
}
```
